discord:
  token: "BOT_TOKEN"
  channelId: "123456789012345678"

chat:
  to-minecraft-prefix: "&3220a6[&7568f9á´…&3220a6] &c9c0ffâ€¢ "

messages:
  discord-to-minecraft:
    - "&897dff{author} &514f5bâ†’ &ddd6ff{message}"

  discord-hover:
    - "&7"
    - "&7bacff â™¯ ĞšĞ°Ğ½Ğ°Ğ»: &3c84ff&l(Ğ½Ğ°Ğ·Ğ²Ğ°Ğ½Ğ¸Ğµ ĞºĞ°Ğ½Ğ°Ğ»Ğ° Ğ² Ğ´Ğ¸ÑĞºĞ¾Ñ€Ğ´Ğµ Ğ´Ğ»Ñ Ğ¼Ğ¾ÑÑ‚Ğ° ÑĞ¾Ğ¾Ğ±Ñ‰ĞµĞ½Ğ¸Ğ¹) "
    - "&798cff âš‘ ĞÑ‚Ğ¿Ñ€Ğ°Ğ²Ğ¸Ñ‚ĞµĞ»ÑŒ: &546cff&l{author} "
    - "&7"
    - "&a9b6ff â€¢ Ğ§Ñ‚Ğ¾Ğ±Ñ‹ Ğ¿ĞµÑ€ĞµĞ¹Ñ‚Ğ¸ Ğº ÑÑ‚Ğ¾Ğ¼Ñƒ ÑĞ¾Ğ¾Ğ±Ñ‰ĞµĞ½Ğ¸Ñ, Ğ½Ğ°Ğ¶Ğ¼Ğ¸Ñ‚Ğµ "
    - "&a9b6ff Ğ½Ğ° Ñ‚ĞµĞºÑÑ‚"
    - "&7"


#
#         *        .        âœ¦          .             .         *
#        .                *        .         âœ·             âœ§        .
#               .        â‹†    *         âœ§         *      â‹†          .
#  â‹†           .        .        â‹†     .             â‹†       .     .
#        âœ·         .       *         âœ¦     â‹†      .     â‹†      *
# .      â‹†    â‹†        .         âœ§       â‹†     âœ¦           â‹†         âœ¦
#        .    â‹†         âœ·             â‹†          â‹†    âœ§      .      â‹†
# âœ·      .        â‹†     .    â‹†      â˜„       â‹†     .     â‹†     âœ§        .
#       .    âœ¦       .      â‹†       â‹†      âœ·        .        â‹†       .
#             â‹†        â‹†        âœ·           .         âœ¦      â‹†
#  â‹†    .       âœ¦       â‹†       .     ğ’·ğ“       âœ·        âœ¦        â‹†       âœ·
#       .         âœ·        â‹†        ğ“ˆğ“ğ“ğ“…ğ’½  .         âœ§    â‹†         â‹†
#   âœ·          .        .      â‹†  ğ’¾ğ“ƒ ï¼’ï¼ï¼’ï¼•  .             â‹†        .      .
#        .          â‹†    *         âœ¦         *      â‹†          .
#            .                *        .         âœ·             âœ§        .
#        âœ·         .       *         âœ¦     â‹†      .     â‹†      *
# .      â‹†    â‹†        .         âœ§       â‹†     âœ¦           â‹†         âœ¦
#        .    â‹†         âœ·             â‹†          â‹†    âœ§      .      â‹†
# âœ·      .        â‹†     .    â‹†      â˜„       â‹†     .     â‹†     âœ§        .
#       .    âœ¦       .      â‹†       â‹†      âœ·        .        â‹†      .
#             â‹†        â‹†        âœ·           .         âœ¦      â‹†
#         *        .        âœ¦          .             .         *
#
